### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by rhakdnj** [rhakdnj/kopring#10]
_**application.yaml**_

```yaml
spring:
  application:
    name: kopring
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  profiles:
    active: ${profile}

message: Hello from Default Profile!

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.springframework: debug

---
# -Dspring.profiles.active=prod
spring:
  config:
    activate:
      on-profile: prod

message: Hello from Production Profile!

---
spring:
  config:
    activate:
      on-profile: test

message: Hello from Test Profile!
```

하나로 관리해도 되며, 여러개로 관리해도 된다.

```yaml
spring:
  profiles:
    include: rdb, security, redis, s3
    active: local
```

- application-dev.yml
- application-prod.yml
- application-rdb.yml
