### ISSUE TITLE
Logging Level Spring Framework

### ISSUE THREAD

**Issue by rhakdnj** [rhakdnj/kopring#9]
```yaml
logging:
  level:
    org.springframework: debug
```
